new file:   setup.py
adsabs/ingest_data_model pull request #2
Opened 2022-02-22 18:46 UTC by seasidesparrow

2022-02-23 22:12 UTC, kelockhart requested changes
Looks good! Just one minor change and then you can merge.

2022-02-23 22:12 UTC, kelockhart commented on setup.py
> +    long_description=__doc__,
I don't actually know what this line would do (which docstring is it pointing to?) - I'd hardcode a string here, or, better, do something like they do here and point to the README: https://packaging.python.org/en/latest/tutorials/packaging-projects/#configuring-metadata (see the example code block in this section)

2022-02-25 12:31 UTC, seasidesparrow commented on setup.py
> +    long_description=__doc__,
Ok, this is fixed.

2022-02-25 14:26 UTC, kelockhart approved these changes
Looks good!

2022-02-25 14:28 UTC, merged